### ISSUE TITLE
I have the below issue when trying to notify my channel.

### ISSUE THREAD

**Issue by PitoneMaledetto** [NDrive/nagios-mattermost#17]
Please let me know if you need further information. Thank you.

VERSIONS:
`python -c "import sys;print sys.executable; import urllib2; print urllib2.__version__"
/usr/bin/python
2.7`

ERROR:
`[1555410523] wproc: NOTIFY job 74314 from worker Core Worker 27615 is a non-check helper but exited with return code 1
[1555410523] wproc:   host=pr-glb-gal-leo-db-01; service=DB Files; contact=mattermost
[1555410523] wproc:   early_timeout=0; exited_ok=1; wait_status=256; error_code=0;
[1555410523] wproc:   stderr line 01: Traceback (most recent call last):
[1555410523] wproc:   stderr line 02:   File "/usr/local/nagios/libexec/mattermost.py", line 108, in <module>
[1555410523] wproc:   stderr line 03:     response = request(args.url, payload(args))
[1555410523] wproc:   stderr line 04:   File "/usr/local/nagios/libexec/mattermost.py", line 102, in request
[1555410523] wproc:   stderr line 05:     response = urllib2.urlopen(req)
[1555410523] wproc:   stderr line 06:   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
[1555410523] wproc:   stderr line 07:     return opener.open(url, data, timeout)
[1555410523] wproc:   stderr line 08:   File "/usr/lib/python2.7/urllib2.py", line 431, in open
[1555410523] wproc:   stderr line 09:     response = self._open(req, data)
[1555410523] wproc:   stderr line 10:   File "/usr/lib/python2.7/urllib2.py", line 454, in _open
[1555410523] wproc:   stderr line 11:     'unknown_open', req)
[1555410523] wproc:   stderr line 12:   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
[1555410523] wproc:   stderr line 13:     result = func(*args)
[1555410523] wproc:   stderr line 14:   File "/usr/lib/python2.7/urllib2.py", line 1265, in unknown_open
[1555410523] wproc:   stderr line 15:     raise URLError('unknown url type: %s' % type)
[1555410523] wproc:   stderr line 16: urllib2.URLError: <urlopen error unknown url type: [http>`

**Comment by PitoneMaledetto** [comment]
[ not needed as per example ]
